Repository VaibhavArora314/StyleShare, pull requests merged in 2024-08, with the labels that each got.

#543 Added borders to testimonials. Issue number #484
  frontend/src/components/TestimonialSlider.tsx
Labels: changes-requested

#546 ✔️Added MIT License in Footer
  frontend/src/components/Footer.tsx
  frontend/src/pages/Policy.tsx
Labels: changes-requested

#551 Feat: Added/fetched user avatar in admin panel successfully issue 548
  admin/src/assets/avatars/avatar1.jpg
  admin/src/assets/avatars/avatar2.jpg
  admin/src/assets/avatars/avatar3.jpg
  admin/src/assets/avatars/avatar4.jpg
  admin/src/assets/avatars/avatar5.jpg
  admin/src/pages/Comments.tsx
  admin/src/pages/Favorites.tsx
  admin/src/pages/Reactions.tsx
  admin/src/pages/Users.tsx
  admin/src/types.ts
  backend/src/routes/admin/controller.ts
  frontend/src/components/TestimonialSlider.tsx
Labels: gssoc, level2

#556 Feat: Added Feedback/Testimonial control in admin panel successfully issue 547
  admin/src/App.tsx
  admin/src/components/SideBar.tsx
  admin/src/pages/UsersFeedbacks.tsx
  admin/src/types.ts
  backend/prisma/schema.prisma
  backend/src/routes/admin/controller.ts
  backend/src/routes/admin/route.ts
  backend/src/routes/user/controller.ts
Labels: gssoc

#542 Designed the Contributors Page Match to Website Theme and Made it Responsive
  frontend/src/pages/Contributors.tsx
Labels: gssoc, level1

#573 Bug: Fixed footer nav links and also restored the scrollbar successfully issue 569
  frontend/src/App.tsx
  frontend/src/pages/Policy.tsx
Labels: gssoc, level1

#571 Add docker compose file to the root of the project
  admin/Dockerfile
  backend/Dockerfile
  docker-compose.yml
  frontend/Dockerfile
Labels: gssoc, level2

#574 Corrected the tag filter + Added placeholder for it + Minor UI Improvements
  frontend/src/components/PostCard.tsx
  frontend/src/pages/EditPost.tsx
  frontend/src/pages/NewPost.tsx
  frontend/src/pages/Posts.tsx
Labels: gssoc, level2

#579 Added skeleton for posts loading
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/PostsSkeleton.tsx
  frontend/src/pages/Posts.tsx
Labels: gssoc

#581 Feat: Added contact messages delete feature for admin successfully issue 575
  admin/src/pages/ContactMessages.tsx
  backend/src/routes/admin/controller.ts
  backend/src/routes/admin/route.ts
Labels: gssoc

#582 Feat: Added delete users feedback feature for admin successfully issue 576
  admin/src/pages/UsersFeedbacks.tsx
  backend/src/routes/admin/controller.ts
  backend/src/routes/admin/route.ts
Labels: gssoc

#585 Bug: Fixed fetch favorite post status code successfully issue 570
  frontend/src/components/PostCard.tsx
Labels: gssoc, level1

#583 added a sort by option on the posts page
  backend/src/routes/post/controller.ts
  frontend/src/hooks/usePosts.tsx
  frontend/src/pages/Posts.tsx
Labels: gssoc, level2

#590 Bug: Fixed Navbar gap at x axis successfully issue 584
  frontend/src/components/Navbar.tsx
Labels: gssoc, level1

#596 Fixed the code page sizings or text and windows
  frontend/src/components/PostCodeWindow.tsx
Labels: gssoc, level1

#593 Added skeleton laoder for code page
  frontend/src/components/CodeSkeleton.tsx
  frontend/src/pages/Post.tsx
Labels: gssoc, level1

#592 Fixed posts card for tablet size 768px
  frontend/src/pages/Posts.tsx
Labels: gssoc, level1

#591 Feat: Added post search suggestion when search on searchbar successfully issue 586
  backend/src/routes/post/controller.ts
  backend/src/routes/post/route.ts
  frontend/src/hooks/usePosts.tsx
  frontend/src/pages/Posts.tsx
Labels: gssoc, level3

#597 Feat: Added Icons in the navbar and fix some navbar bugs and structure successfully issue 311
  frontend/src/components/Navbar.tsx
Labels: gssoc, level1
