Repository VaibhavArora314/StyleShare, pull requests merged in 2024-07, with the labels that each got.

#368 Feat: Added Preloader in edit post successfully Issue 363
  frontend/src/pages/EditPost.tsx
  frontend/src/pages/Signin.tsx
Labels: gssoc, level1

#387 Feat: Creating API/fetching in card status successfully Issue 365
  admin/src/components/StatusCard.tsx
  backend/src/routes/admin/controller.ts
  backend/src/routes/admin/route.ts
Labels: gssoc, level2

#423 Feat: Added favicon and title on every tab successfully issue 416
  admin/index.html
  admin/src/components/SideBar.tsx
  admin/src/pages/Dashboard.tsx
  admin/src/pages/PageNotFound.tsx
  admin/src/pages/Posts.tsx
  admin/src/pages/Profile.tsx
  admin/src/pages/Signin.tsx
  admin/src/pages/Users.tsx
Labels: gssoc, level1

#422 Bug: Fixed the margin in favorite posts page successfully issue 415
  frontend/src/pages/Favorite.tsx
Labels: gssoc, level1

#425 Feat: Added graphs(Line, Bar, Bubble, Scatter) for admin successfully issue 367
  admin/package-lock.json
  admin/package.json
  admin/src/App.tsx
  admin/src/components/SideBar.tsx
  admin/src/pages/Graphs.tsx
  backend/prisma/schema.prisma
  backend/src/routes/admin/controller.ts
  backend/src/routes/admin/route.ts
  backend/src/routes/post/controller.ts
Labels: gssoc

#427 Updated contact-us Page
  frontend/src/assets/Contact-us.png
  frontend/src/assets/Contact-us1.png
  frontend/src/assets/Contact-us2.png
  frontend/src/pages/ContactUs.tsx
Labels: gssoc

#430 Added Github link in Contributor
  frontend/src/pages/Contributors.tsx
Labels: gssoc, level1

#432 Bug: Fixed the page not found text in light/dark mode successfully issue 429
  admin/src/pages/PageNotFound.tsx
  frontend/src/App.tsx
  frontend/src/pages/PageNotFound.tsx
Labels: gssoc, level1

#431 Feat: Added managing contact messages from admin successfully issue 426
  admin/package-lock.json
  admin/package.json
  admin/src/App.tsx
  admin/src/components/SideBar.tsx
  admin/src/index.css
  admin/src/pages/ContactMessages.tsx
  admin/src/pages/Posts.tsx
  admin/src/styles/Model.css
  admin/src/types.ts
  backend/src/routes/admin/controller.ts
  backend/src/routes/admin/route.ts
Labels: gssoc

#445 Feat: Added link to table and card in admin dashboard successfully issue 439
  admin/src/components/NewPosts.tsx
  admin/src/components/SideBar.tsx
  admin/src/components/StatusCard.tsx
  admin/src/components/TrendingPosts.tsx
Labels: gssoc

#443 Feat: Added lazy loading for cards and loader for tables in admin panel successfully issue 438
  admin/package-lock.json
  admin/package.json
  admin/src/components/NewPosts.tsx
  admin/src/components/StatusCard.tsx
  admin/src/components/TrendingPosts.tsx
  admin/src/pages/ContactMessages.tsx
  admin/src/pages/Graphs.tsx
  admin/src/pages/Posts.tsx
  admin/src/pages/Users.tsx
Labels: gssoc

#466 Feat: Added Google translator in admin panel successfully issue 364
  admin/src/App.tsx
  admin/src/components/GoogleTranslate.tsx
  admin/src/components/Layout.tsx
  admin/src/components/Navbar.tsx
  admin/src/components/SideBar.tsx
  admin/src/components/UpdatePost.tsx
  admin/src/pages/Comments.tsx
  admin/src/pages/ContactMessages.tsx
  admin/src/pages/Dashboard.tsx
  admin/src/pages/Graphs.tsx
  admin/src/pages/Posts.tsx
  admin/src/pages/Profile.tsx
  admin/src/pages/Users.tsx
  admin/src/styles/Translate.css
Labels: gssoc

#467 Bug: Modified the whole navbar and adjust the google translator button successfully issue 462
  frontend/src/App.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/styles/Translate.css
Labels: gssoc

#470 Feat: Added scroll down progress in style share successfully issue 469
  frontend/src/App.tsx
  frontend/src/components/ProgressScrollDown.tsx
Labels: enhancement, gssoc, level1

#483 Select Language hide after some scroll
  frontend/src/components/GoogleTranslate.tsx
  frontend/src/styles/Translate.css
Labels: gssoc, level1

#480 Feat: Updated update profile form UI and removed facebook link from frontend successfully Issue 475
  backend/prisma/schema.prisma
  backend/src/routes/user/controller.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/profileForm.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/ShowProfile.tsx
  frontend/src/styles/Model.css
  frontend/src/types.ts
Labels: gssoc, level1

#482 FIX: Make the post card clickable
  frontend/package-lock.json
  frontend/src/components/PostCard.tsx
Labels: gssoc, level1

#490 Bug: Fixed the extra margin between policy page and navbar successfully issue 486
  frontend/src/pages/Policy.tsx
Labels: gssoc, level1

#489 Feat: Added hover effect on user profile social icons successfuly issue 485
  frontend/src/pages/Profile.tsx
  frontend/src/pages/ShowProfile.tsx
Labels: gssoc, level1

#488 Feat: Added users avatar feature in profile successfully Issue 411
  backend/package-lock.json
  backend/package.json
  backend/prisma/schema.prisma
  backend/src/routes/post/controller.ts
  backend/src/routes/user/controller.ts
  backend/src/routes/user/zodSchema.ts
  frontend/src/assets/avatars/avatar1.jpg
  frontend/src/assets/avatars/avatar2.jpg
  frontend/src/assets/avatars/avatar3.jpg
  frontend/src/assets/avatars/avatar4.jpg
  frontend/src/assets/avatars/avatar5.jpg
  frontend/src/components/Navbar.tsx
  frontend/src/components/profileForm.tsx
  frontend/src/pages/Comment.tsx
  frontend/src/pages/LeaderBoard.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/ShowProfile.tsx
  frontend/src/types.ts
Labels: gssoc, level2

#496 ✔️Improved the "FAQ Section" of the Website.
  frontend/src/components/FAQ.tsx
Labels: changes-requested

#505 Feat #502 added hovering effect on socials
  frontend/src/components/SharePostButtons.tsx
Labels: gssoc, level1

#506 Fixes the Like button in the postcard
  frontend/src/components/PostCard.tsx
Labels: gssoc, level1

#510 Feat: Added showing admin which user marked favorite to which post successfully issue 500
  admin/src/App.tsx
  admin/src/components/SideBar.tsx
  admin/src/pages/Favorites.tsx
  admin/src/types.ts
  backend/src/routes/admin/controller.ts
  backend/src/routes/admin/route.ts
Labels: enhancement, gssoc, level3

#515 Feat: Added preloader in style share successfully issue 412
  frontend/src/App.tsx
  frontend/src/components/PreLoader.tsx
  frontend/src/index.css
Labels: gssoc

#514 Feat: Redirect to user profile on click of entire row in leaderboard successfully issue 404
  frontend/src/pages/LeaderBoard.tsx
Labels: gssoc, level1

#512 feat update:non copyable captcha added
  frontend/src/assets/captcha.webp
  frontend/src/components/CaptchaUser.tsx
  frontend/src/styles/captcha.css
Labels: gssoc, changes-requested

#532 Feat: Added Tab title, captcha non copyable and clickable card stats in admin panel successfully issue 531
  admin/index.html
  admin/src/assets/captcha.webp
  admin/src/components/CaptchaAdmin.tsx
  admin/src/components/StatusCard.tsx
  admin/src/styles/captcha.css
Labels: gssoc, level1

#533 Feat: Integrated the feedback with the Testimonial in style share successfully issue 526
  backend/src/routes/user/controller.ts
  backend/src/routes/user/route.ts
  frontend/src/components/TestimonialSlider.tsx
Labels: gssoc
