Repository VaibhavArora314/StyleShare, pull requests merged in 2024-06, with the labels that each got.

#42 Created CODE_OF_CONDUCT.md and PR_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
Labels: gssoc, level1

#84 [FEAT]: Created Issue forms and made the issue options more visually appealing
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/documentation_update.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc, level1

#86 Made changes in footer
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Footer.tsx
  frontend/src/pages/About.tsx
  frontend/src/pages/ContactUs.tsx
  frontend/src/pages/Policy.tsx
Labels: gssoc, level1

#165 feat: Added Multilanguage feature in overall webapp successfully issue 149
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/components/Footer.tsx
  frontend/src/components/HeroText.tsx
  frontend/src/components/LanguageDropdown.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/i18n.ts
  frontend/src/locales/en/translation.json
  frontend/src/locales/guj/translation.json
  frontend/src/locales/hi/translation.json
  frontend/src/locales/mh/translation.json
  frontend/src/locales/tam/translation.json
  frontend/src/locales/tel/translation.json
  frontend/src/locales/ur/translation.json
  frontend/src/locales/wb/translation.json
  frontend/src/pages/About.tsx
  frontend/src/pages/Comment.tsx
  frontend/src/pages/CustomizeWithAi.tsx
  frontend/src/pages/Favorite.tsx
  frontend/src/pages/Home.tsx
  frontend/src/pages/HomePagePosts.tsx
  frontend/src/pages/LeaderBoard.tsx
  frontend/src/pages/NewPost.tsx
  frontend/src/pages/PageNotFound.tsx
  frontend/src/pages/Post.tsx
  frontend/src/pages/Posts.tsx
  frontend/src/pages/Profile.tsx
  frontend/src/pages/Signin.tsx
  frontend/src/pages/Signup.tsx
Labels: gssoc, level3

#204 feat: Added edit profile in profile section cards successfully issue 195
  frontend/src/App.tsx
  frontend/src/components/EditPost.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/pages/Post.tsx
Labels: gssoc, level2
